name: pos_ai_sales
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.4
  firebase_messaging: ^16.0.4
  uuid: ^4.5.2
  connectivity_plus: ^7.0.0
  go_router: ^17.0.0
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  excel: ^4.0.6
  csv: ^6.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  intl: ^0.20.2
  image: ^4.3.0
  fl_chart: ^0.68.0
  usb_thermal_printer_web: ^0.0.3
  # sqflite_common_ffi: ^2.3.6
  # sqflite_common_ffi_web: ^1.0.1+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true




